BOOTLOADER = atmel-dfu

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = no
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
COMBO_ENABLE = yes
AUTO_SHIFT_ENABLE = no
ENCODER_MAP_ENABLE = yes

SPACE_CADET_ENABLE = no
BOOTMAGIC_ENABLE = no

#POINTING_DEVICE_ENABLE = yes
#POINTING_DEVICE_DRIVER = pimoroni_trackball
#POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

SPLIT_KEYBOARD = yes
