#CONVERT_TO=elite_pi
PIN_COMPATIBLE = elite_c

BOOTLOADER = caterina
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes
COMBO_ENABLE = yes
RGBLIGHT_ENABLE = yes
ENCODER_MAP_ENABLE = yes
OLED_ENABLE = no
OLED_DRIVER = SSD1306
